cart/urls.py
from django.urls import path

from .views import *

app_name = 'cart'

urlpatterns = [
    path('', detail, name='detail'),
    path('add/<int:product_id>', add, name='add'),
    path('remove/<int:product_id>', remove, name='remove'),
]

coupon/urls.py
from django.urls import path
from .views import add_coupon

app_name='coupon'

urlpatterns = [
    path('add/', add_coupon, name='add'),
]

onlineshop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('cart/', include('cart.urls')),
    path('coupon/', include('coupon.urls')),
    path('order/', include('order.urls')),
    path('', include('shop.urls')),
]

order/urls.py
from django.urls import path
from .views import *

app_name = 'orders'

urlpatterns = [
    path('create/', order_create, name='order_create'),
    path('create_ajax/', OrderCreateAjaxView.as_view(), name='order_create_ajax'),
    path('checkout/', OrderCheckoutJajaxView.as_view(), name='order_checkout'),
    path('validation/', OrderImpAjaxView.as_view(), name='order_validation'),
    path('complete/', order_complete, name='order_complete'),

]

shop/urls.py
from django.urls import path
from .views import *

app_name = 'shop'

urlpatterns = [
    path('', product_in_category, name='product_all'),
    path('<slug:category_slug>/', product_in_category, name='product_in_category'),
    path('<int:id>/<product_slug>/', product_detail, name='product_detail'),
]

cart/models.py
from django.db import models
from decimal import Decimal
from django.conf import settings
from shop.models import Product

class Cart(object):
    def __init__(self, request):
        self.session = request.session
        cart = self.session.get(settings.CART_ID)
        if not cart:
            cart = self.session[settings.CART_ID] = {}
        self.cart = cart


    def __len__(self):
        return sum(item['quantity'] for item in self.cart.values())

    def __iter__(self):
        product_ids = self.cart.keys()

        products = Product.objects.filter(id__in=product_ids)

        for product in products:
            self.cart[str(product.id)]['product'] = product

        for item in self.cart.values():
            item['price'] = Decimal(item['price'])
            item['total_price'] = item['price'] * item['quantity']

            yield item

    def add(self, product, quantity=1, is_update=False):
        product_id = str(product.id)
        if product_id not in self.cart:
            self.cart[product_id] = {'quantity':0, 'price':str(product.price)}

        if is_update:
            self.cart[product_id]['quantity'] = quantity
        else:
            self.cart[product_id]['quantity'] = quantity+1

        self.save()

    def save(self):
        self.session[settings.CART_ID] = self.cart
        self.session.modified = True

    def remove(self, product):
        product_id = str(product.id)
        if product_id in self.cart:
            del(self.cart[product_id])
            self.save()

    def clear(self):
        self.session[settings.CART_ID] = {}
        self.session.modified = True

    def get_product_total(self):
        return sum(Decimal(item['price'])*item['quantity'] for item in self.cart.values())

cart/forms.py
from django import forms

class AddProductForm(forms.Form):
    quantity = forms.IntegerField()
    is_update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.utils import timezone

from shop.models import Product
from .forms import AddProductForm
from .models import *
from coupon.forms import AddCouponForm

@require_POST
def add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)

    form = AddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], is_update=cd['is_update'])

    return redirect('cart:detail')


def remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:detail')


def detail(request):
    cart = Cart(request)
    add_coupon = AddCouponForm()
    for product in cart:
        product['quantity_form'] = AddProductForm(initial={'quantity':" product['quantity'], 'is_update': True"})

    return render(request, 'cart/detail.html', {'cart': cart, 'add_coupon': add_coupon})

cart/templates/cart/detail.html
{% extends 'base.html' %}

{% block title %}
  Shopping Cart
{% endblock %}

{% block content %}
<table class="table table-striped">
    <thead>
        <tr>
            <th>Image</th>
            <th>Product</th>
            <th>Quantity</th>
            <th>Remove</th>
            <th>Unit Price</th>
            <th>Price</th>
        </tr>
    </thead>
    <tbody>
        {% for item in cart %}
            {% with product=item.product %}
        <tr>
          <th scope="row">
            <a href="{{product.get_absolute_url}}">
              <img src="{{product.image.url}}" class="img-thumbnail"></a>
          </th>
          <td>{{ product.name }}</td>
          <td>
                <form action="{% url 'cart:add' product.id %}" method="post">
                    {{item.quantity}}
                    {{item.quantity_form.is_update}}
                    <input type="submit" class="btn btn-primary" value="Update">
                    {% csrf_token %}
                </form>
          </td>
          <td><a href="{% url 'cart:remove' product.id %}" class="btn btn-sm btn-outline-warning">remove</a></td>
          <td>${{ product.price }}</td>
          <td>${{ product.quantity }}</td>
        </tr>
            {% endwith %}
        {% endfor %}

        {% if cart.coupon %}
          <tr class="subtotal">
            <td>Subtotal</td>
            <td colspan="4"></td>
            <td>${{ cart.get_product_total }}</td>
          </tr>
          <tr>
              <td>"{{ cart.coupon.code }}" coupon (${{ cart.coupon.amount }})</td>
              <td colspan="4"></td>
              <td>- ${{ cart.get_discount_total|floatformat:"2" }}</td>
            </tr>
        {% endif %}

        <tr class="total">
          <td>Total</td>
          <td colspan="4"></td>
          <td class="num">${{ cart.get_total_price|floatformat:"2" }}</td>
        </tr>

    </tbody>
</table>

<p>Add Coupon:</p>

<form action='{% url "coupon:add" %}' method="post">
  {{ add_coupon }}
  <input type="submit" value="Add">
  {% csrf_token %}
</form>

  <p class="text-right">
    <a href='{% url "shop:product_all" %}' class="btn btn-secondary">Continue shopping</a>
    <a href='{% url "orders:order_create" %}' class="btn btn-primary">Checkout</a>
  </p>
{% endblock %}